name: OnamerilBouwServer
description: Plugin voor de bouwserver van Onameril
author: Hotseflots
version: 1.1.2
main: nl.hotseflots.onabouwserver.Main
depend:
  - ActionBarAPI
commands:
  staffmode:
    description: Enter staffmode
    usage: /staffmode
    aliases:
      - sm
  buildmode:
    description: Enter buildmode
    aliases:
      - bm
  freeze:
    description: Freeze player
  unfreeze:
    description: Unfreeze player
  commandhistory:
    description: See history of commands from player
    aliases:
      - cmhistory
      - cmh
      - chistory